#server:
#  port: 9005

spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: dev


# ***********************************************************************
# Moved configurations to config server
# ***********************************************************************





#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/user_db
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
#  jwt:
#    secret: ${JWT_SECRET}
#    accessTokenExpiration: 900
#    refreshTokenExpiration: 604800
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: false
