#server:
#  port: 9001

spring:
  application:
    name: category-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: dev

#    ***********************************************************************
#    Moved all other configurations to config server
#    ***********************************************************************


#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/fingcart_category_db
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    preferIpAddress: false
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info
#  endpoint:
#    health:
#      show-details: always
