server:
  port: 9001

spring:
  application:
    name: category-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fingcart_category_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
